package br.com.vitxr.lambdausers.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "users")
public class User implements Serializable {

    @DynamoDBHashKey (attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private Long id;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String password;
    @DynamoDBAttribute
    private int age;
    @DynamoDBAttribute
    private double weight;
    @DynamoDBAttribute
    private double heigth;
}
